# Generated by Django 4.2.2 on 2023-09-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_album_artist_genre_song_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='image_url',
            field=models.FileField(default=1, upload_to='playlistImg/'),
            preserve_default=False,
        ),
    ]
