# Generated by Django 4.2.2 on 2023-09-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_playlist_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='image_url',
            field=models.FileField(blank=True, null=True, upload_to='playlistImg/'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.song'),
        ),
    ]
